### ISSUE TITLE
README examples use old Actions syntax

### ISSUE THREAD

**Issue by Nadock** [JasonEtco/upload-to-release#10]
Re: the discussion in PR #9 

The examples in the `README.md` use the old Actions syntax, suggest updating them to the new `yaml` based syntax.

On a related point, I think the `README.md` should also call out specifically that this action will only work with the `release` event type, not any other event type (like `push` for example).

**Comment by tenhobi** [comment]
This would be awesome to have!

**Comment by JasonEtco** [comment]
Thanks for opening this @Nadock - PRs welcome 🙏 Otherwise, I'd recommend using https://github.com/actions/upload-release-asset instead!
