### ISSUE TITLE
The action doesn't fail when API call fails

### ISSUE THREAD

**Issue by c-brooks** [JasonEtco/upload-to-release#15]
Hi 👋 thanks for your work! We're using this as part of our release workflow, and noticed today that the GitHub API upload call returned a `Not found`. We've never seen this before, and couldn't reproduce the issue, but it showed us that the action finished successfully. We expect that the action should fail here if the API call fails.

Logs:

```sh
> Run JasonEtco/upload-to-release@master
/usr/bin/docker run --name dfbe11167ca24c24fd4bc70170aa97ccebd_658105 --label 488dfb --workdir /github/workspace --rm -e GITHUB_TOKEN -e INPUT_ARGS -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/insights-releases/insights-releases":"/github/workspace" 488dfb:e11167ca24c24fd4bc70170aa97ccebd installation.tgz application/gzip
https://uploads.github.com/repos/github/insights-releases/releases/22876496/assets?name=installation.tgz
{"message":"Not Found","request_id":"07C0:4090:4A70F:5CE27:5E1F9B63","documentation_url":"https://developer.github.com/v3"}
```

**Comment by JasonEtco** [comment]
Hey @c-brooks, thanks for the report! This is the first I'm hearing of this, but it sounds plausible; thanks for the detailed logs.

This action is largely a wrapper around `curl`; I would expect `curl` to `exit > 0` if the request fails, but we might need to do some more detailed parsing, or look at the response code. Here's where that code lives:

https://github.com/JasonEtco/upload-to-release/blob/976a0be3dd6c5b266a6885ceb327548df575f293/upload-to-release#L47-L54

I'm not a bash expert, so if you're up for a PR that would be wonderful!

**Comment by c-brooks** [comment]
Sure thing @JasonEtco, I'll see if I can open a PR this weekend 👍
